# This crate should NOT be upstreamed to crates.io; it is only intended for 
# PARSEC testing purposes (both locally and on CI)
[package]
name = "e2e_tests"
version = "0.1.0"
authors = ["Anton Antonov <anton.antonov@arm.com>",
           "Paul Howard <paul.howard@arm.com>",
           "Ionut Mihalcea <ionut.mihalcea@arm.com>",
           "Hugues de Valon <hugues.devalon@arm.com>"]
description = "End to end testing framework for PARSEC"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
serde = { version = "1.0.115", features = ["derive"] }
parsec-client = { git = "https://github.com/parallaxsecond/parsec-client-rust", rev = "dbd449a9e736f9f972e5489fb2d67949b93484dc", features = ["testing"] }
log = "0.4.11"
rand = "0.7.3"

[dev-dependencies]
ring = "0.16.15"
env_logger = "0.7.1"
rsa = "0.3.0"
picky-asn1-x509 = "0.3.2"
base64 = "0.12.3"
num_cpus = "1.13.0"
picky-asn1-der = "0.2.4"
picky-asn1 = "0.3.0"
sha2 = "0.9.1"

[features]
mbed-crypto-provider = []
tpm-provider = []
pkcs11-provider = []
all-providers = ["pkcs11-provider","tpm-provider","mbed-crypto-provider"]
